// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Saturday_Back.Common.Database;

#nullable disable

namespace Saturday_Back.Migrations
{
    [DbContext(typeof(FssDbContext))]
    [Migration("20251201171933_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Saturday_Back.Features.BaseCosts.BaseCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rec_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cost");

                    b.Property<string>("StudyYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("study_year");

                    b.HasKey("Id");

                    b.HasIndex("StudyYear")
                        .IsUnique();

                    b.ToTable("base_costs", (string)null);
                });

            modelBuilder.Entity("Saturday_Back.Features.BenefitTypes.BenefitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rec_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("benefit_types", (string)null);
                });

            modelBuilder.Entity("Saturday_Back.Features.PaymentTypes.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rec_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("payment_types", (string)null);
                });

            modelBuilder.Entity("Saturday_Back.Features.Schedules.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rec_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseCostId")
                        .HasColumnType("int")
                        .HasColumnName("basecostid");

                    b.Property<int>("BenefitTypeId")
                        .HasColumnType("int")
                        .HasColumnName("benefittypeid");

                    b.Property<int>("FirstMonth")
                        .HasColumnType("int")
                        .HasColumnName("firstmonth");

                    b.Property<int>("FirstSaturday")
                        .HasColumnType("int")
                        .HasColumnName("firstsaturday");

                    b.Property<int>("LastMonth")
                        .HasColumnType("int")
                        .HasColumnName("lastmonth");

                    b.Property<int>("LastSaturday")
                        .HasColumnType("int")
                        .HasColumnName("lastsaturday");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("paymenttypeid");

                    b.Property<string>("ScheduleEntries")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("schedule_entries");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subjectid");

                    b.HasKey("Id");

                    b.HasIndex("BaseCostId");

                    b.HasIndex("BenefitTypeId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("SubjectId");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("Saturday_Back.Features.Students.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rec_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdmissionYearId")
                        .HasColumnType("int")
                        .HasColumnName("admissionyearid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("Identificator")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("identificator");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lastname");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionYearId");

                    b.HasIndex("Identificator")
                        .IsUnique();

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("Saturday_Back.Features.StudyYears.StudyYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rec_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("YearRange")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("yearrange");

                    b.HasKey("Id");

                    b.HasIndex("YearRange")
                        .IsUnique();

                    b.ToTable("study_years", null, t =>
                        {
                            t.HasCheckConstraint("CK_StudyYear_YearRange_Format", "`yearrange` REGEXP '^[0-9]{4}-[0-9]{4}$'");
                        });
                });

            modelBuilder.Entity("Saturday_Back.Features.Subjects.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rec_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("Saturday_Back.Features.Schedules.Schedule", b =>
                {
                    b.HasOne("Saturday_Back.Features.BaseCosts.BaseCost", "BaseCost")
                        .WithMany()
                        .HasForeignKey("BaseCostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saturday_Back.Features.BenefitTypes.BenefitType", "BenefitType")
                        .WithMany()
                        .HasForeignKey("BenefitTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saturday_Back.Features.PaymentTypes.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saturday_Back.Features.Subjects.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseCost");

                    b.Navigation("BenefitType");

                    b.Navigation("PaymentType");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Saturday_Back.Features.Students.Student", b =>
                {
                    b.HasOne("Saturday_Back.Features.StudyYears.StudyYear", "AdmissionYear")
                        .WithMany("Students")
                        .HasForeignKey("AdmissionYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdmissionYear");
                });

            modelBuilder.Entity("Saturday_Back.Features.StudyYears.StudyYear", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
